browser/urls.py
from browser.views import *
from django.conf.urls import url

urlpatterns = [
    url(r'^$', SalaryRecordListView.as_view(), name='home'),
    url(r'^context/$', ContextView.as_view(), name='context'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^person/(?P<slug>[-\w]+)/$', PersonDetailView.as_view(), name='person_detail'),
    url(r'^departments/$', DepartmentListView.as_view(), name='department_list'),
    url(r'^departments/(?P<slug>[-\w]+)/$', DepartmentDetailView.as_view(), name='department_detail'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from browser.views import *

urlpatterns = [
    url(r'^paychecker/', include('browser.urls')),
]

salary/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.postgres.fields import ArrayField


class SalaryRecord(models.Model):
    """
    Individual salary record for one person in one year.
    """
    year = models.CharField(max_length=4)
    location = models.CharField(max_length=256, null=True)
    first = models.CharField(max_length=256, null=True)
    middle = models.CharField(max_length=256, null=True)
    last = models.CharField(max_length=256, null=True)
    name = models.CharField(max_length=256, null=True)
    title = models.CharField(max_length=256, null=True)
    title_category = models.CharField(max_length=256, null=True)
    title_qualifier = models.CharField(max_length=256, null=True)
    title_year_code = models.CharField(max_length=16, null=True)
    gross = models.DecimalField(null=True, decimal_places=2, max_digits=20)
    regular = models.DecimalField(null=True, decimal_places=2, max_digits=20)
    overtime = models.DecimalField(null=True, decimal_places=2, max_digits=20)
    other = models.DecimalField(null=True, decimal_places=2, max_digits=20)
    base = models.DecimalField(null=True, decimal_places=2, max_digits=20)
    eff_date = models.CharField(max_length=16, null=True)

    person = models.ForeignKey('Person', null=True)

    def __str__(self):
        return '{}: {}'.format(self.name, self.year)

    class Meta:
        ordering = ['-year']


class DirectoryRecord(models.Model):
    """
    Individual record from the online Berkeley directory. Possibly
    belongs to a Department.
    """
    searched_name = models.CharField(max_length=256, null=True)
    directory_name = models.CharField(max_length=256, null=True)
    title = models.CharField(max_length=256, null=True)
    department = models.CharField(max_length=256, null=True)
    home_department = models.CharField(max_length=256, null=True)
    uid = models.CharField(max_length=256, null=True)
    success = models.BooleanField(default=False)

    department_obj = models.ForeignKey('Department', null=True)

    def __str__(self):
        return self.searched_name

    class Meta:
        ordering = ['person__last']


class Department(models.Model):
    """
    An academic department, which contains DirectoryRecords
    and may have multiple codes.
    """
    codes = ArrayField(models.CharField(max_length=5), null=True)
    desc = models.CharField(max_length=256, null=True)
    canonical = models.CharField(max_length=256)
    discipline = models.CharField(max_length=256, null=True)
    slug = models.CharField(max_length=256, null=True)

    def get_absolute_url(self):
        return '/paychecker/departments/{}/'.format(self.slug)

    @property
    def avg_salary_2015(self):
        return SalaryRecord.objects.filter(
            person__directory_record__department_obj=self).filter(year='2015').aggregate(models.Avg('gross'))['gross__avg']

    def avg_salary_by_category(self, category):
        return SalaryRecord.objects.filter(person__directory_record__department_obj=self).filter(title_category=category).filter(year='2015').aggregate(models.Avg('gross'))['gross__avg']

    @property
    def avg_salary_professor(self):
        return self.avg_salary_by_category('professor')

    @property
    def avg_salary_associate_professor(self):
        return self.avg_salary_by_category('associate professor')

    @property
    def avg_salary_assistant_professor(self):
        return self.avg_salary_by_category('assistant professor')

    @property
    def avg_salary_lecturer(self):
        return self.avg_salary_by_category('lecturer')

    def __str__(self):
        return self.canonical


class Person(models.Model):
    """
    A person with one or more SalaryRecords and possibly
    one DirectoryRecord.
    """
    first = models.CharField(max_length=256, null=True)
    last = models.CharField(max_length=256, null=True)
    slug = models.CharField(max_length=256, null=True)

    search_attempt = models.BooleanField(default=False)
    directory_record = models.OneToOneField('DirectoryRecord', null=True)

    @property
    def latest_record(self):
        return self.salaryrecord_set.first()

    def get_absolute_url(self):
        return '/paychecker/person/{}/'.format(self.slug)

    def save(self, *args, **kwargs):
        self.slug = slugify('{} {}'.format(self.first, self.last))
        super(Person, self).save(*args, **kwargs)

    def __str__(self):
        return '{}, {}'.format(self.last, self.first)

    class Meta:
        ordering = ['last']

browser/views.py
import os
from django.shortcuts import render
from django.utils.text import slugify
from bakery.views import BuildableTemplateView, BuildableListView, BuildableDetailView
from salary.models import Person, Department, SalaryRecord, DirectoryRecord
from django.db.models import Avg


class SalaryRecordListView(BuildableListView):
    """
    The landing page, with a full list of people.
    """
    model = SalaryRecord
    template_name = 'browser/home.html'
    build_path = 'paychecker/index.html'

    def get_queryset(self):
        return self.model.objects.filter(year='2015').exclude(person__directory_record__department_obj=None)


class ContextView(BuildableTemplateView):
    template_name = 'browser/context.html'
    build_path = 'paychecker/context/index.html'


class AboutView(BuildableTemplateView):
    template_name = 'browser/about.html'
    build_path = 'paychecker/about/index.html'


class PersonDetailView(BuildableDetailView):
    """
    All salary and department information for an individual person.
    """
    model = Person
    template_name = 'browser/person_detail.html'


class DepartmentListView(BuildableListView):
    """
    List of departments with salary by position.
    """
    model = Department
    template_name = 'browser/department_list.html'
    build_path = 'paychecker/departments/index.html'


class DepartmentDetailView(BuildableDetailView):
    """
    Average salary by position, and a full list of people for a department.
    """
    model = Department
    template_name = 'browser/department_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DepartmentDetailView, self).get_context_data(**kwargs)
        context['by_title_category'] = SalaryRecord.objects.filter(year=2015).filter(person__directory_record__department_obj=self.object).values('title_category').annotate(Avg('gross')).order_by('gross__avg').reverse()
        for d in context['by_title_category']:
            d['all__avg'] = SalaryRecord.objects.filter(year=2015).filter(title_category=d['title_category']).aggregate(Avg('gross'))['gross__avg']

        context['by_year'] = []
        for year in range(2006, 2016):
            year = str(year)
            avg = SalaryRecord.objects.filter(year=year).filter(person__directory_record__department_obj=self.object).aggregate(Avg('gross'))['gross__avg']
            berkeley_avg = SalaryRecord.objects.filter(year=year).aggregate(Avg('gross'))['gross__avg']
            context['by_year'].append({
                'year': year,
                'avg': avg,
                'berkeley_avg': berkeley_avg
            })

        return context

browser/templates/browser/about.html
{% extends 'browser/base.html' %}

{% block title %} About | {{ block.super }} {% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}">Home</a></li>
<li class="active">About</li>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-8">
	<h2 id="data">About the data</h2>

	<h3>Salary scales</h3>
	<p>The university publishes <a href="http://www.ucop.edu/academic-personnel-programs/compensation/2016-17-academic-salary-scales.html">salary scales</a> for its faculty members that incorporate their "rank" — from lowest to highest: assistant professor, associate professor or professor — and provide additional guidance based on the time a person has spent at that rank.</p>

	<p>But compensation decisions are largely discretionary, and in many cases an individual's year-to-year pay doesn't follow the progression laid out in the salary scales.</p>

	<p>"Generally, a number of factors influence the individual salary data in UC’s database, including the employee’s position, performance, scope of responsibilities, knowledge, experience, duration of employment at UC, and whether it is a full-time or part-time appointment, summer salary, or approved additional compensation, among other considerations," said UC spokesperson Claire Doan in an email.</p>

	<p>This means a professor or lecturer’s salary might decrease from year to year or increase dramatically, even if they maintain the same rank.</p>

	<p>In particular, salaries for part-time lecturers can be pro-rated based on the amount of time they spend teaching, Doan said. This is one reason why salaries for part-time lecturers can be a few thousand dollars while those for full-time, senior lecturers can be more than $250,000.</p>

	<h3 id="caveats">Caveats</h3>
	<p>We're only analyzing full professors, assistant professors, associate professors and lecturers. We've dropped information about administrators, deans, adjunct professors, lecturers for the summer session and others. We couldn't associate all faculty members with a department, and we've chosen to exclude those people from this website (they're still available in our <a href="https://github.com/dailycal-projects/ucb-faculty-salary/tree/master/data">processed data</a>).</p>

	<p>Also, an individual’s salary can vary year-to-year based on the portion of time they spend on campus. Some salaries are based on the academic year and some on the fiscal year. Making departmental comparisons is especially difficult because some departments may have more experienced faculty who would consequently be paid more.</p>

	<p>Another technical note: In all cases, we're examining the faculty member's gross salary, which is the total amount they were paid by the university. Their base salary might be different.</p>

	<p>Finally, we've merged salary and departmental information by matching the first and last names of individuals. That automatic process might fail for people with similar names. If you spot an error, <a href="mailto:projects@dailycal.org">let us know</a>.</p>


	<hr>

	<h2 id="project">About this project</h2>

	<h3>Why another salary database?</h3>
	<p>The university publishes employee pay data <a href="https://ucannualwage.ucop.edu/wage/">on its website</a> annually. But it doesn't have information on faculty departmental affiliations, and it's not easy to trace a person's salary over multiple years.</p>

	<p>We merged data from 2010 to 2015 from the university with 2006 to 2009 pay data from the UC Berkeley Library. Then we added information about departmental affiliations from the UC Berkeley directory, where available. The result is the most complete public, downloadable database of pay information for the UC Berkeley faculty.</p>

	<h3 id="download">Download and contribute</h3>
	<p>We're publishing the raw data and code used to create this database for journalists and researchers. Our pipeline can be used to analyze data from other campuses or even for other positions within the university — for example, administrators or athletic personnel.</p>
	<p>This project is a work in progress. You can read more details and contribute <a href="https://github.com/dailycal-projects/ucb-faculty-salary">on GitHub.</a></p>
</div>
</div>
{% endblock %}

browser/templates/browser/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Professor pay-checker | The Daily Californian{% endblock %}</title>
    {% block meta %}
        <meta charset="utf-8" />
        <meta name="description" content="{% block description %}The most complete open-source database of UC Berkeley faculty salaries by department.{% endblock %}" />
        <meta name="keywords" content="{% block keywords %}dailycal, Daily Californian, Daily Cal, faculty, salary, pay, compensation, payroll, database, open-source{% endblock %}" />
        <link rel='shortcut icon' href='http://www.dailycal.org/assets/uploads/2012/02/favicon.png'/>
        <meta name="twitter:card" content="summary"/>
        <meta name="twitter:description" content="The most complete open-source database of UC Berkeley faculty salaries by department."/>
        <meta name="twitter:title" content="Professor pay-checker | The Daily Californian"/>
        <meta name="twitter:site" content="@dailycal"/>
        <meta name="twitter:domain" content="The Daily Californian"/>
        <meta name="twitter:image" content="http://i0.wp.com/www.dailycal.org/assets/uploads/2014/04/fbimage1410x738.png"/>
        <meta name="twitter:creator" content="@dailycal"/>
        <meta property="og:locale" content="en_US"/>
        <meta property="og:type" content="article"/>
        <meta property="og:title" content="Professor pay-checker | The Daily Californian"/>
        <meta property="og:url" content="http://projects.dailycal.org/paychecker/"/>
        <meta property="og:type" content="article"/>
        <meta property="og:description" content="The most complete open-source database of UC Berkeley faculty salaries by department."/>
        <meta property="og:image" content="http://i0.wp.com/www.dailycal.org/assets/uploads/2014/04/fbimage1410x738.png"/>
        <meta property="og:image:width" content="1410">
        <meta property="og:image:height" content="738">
        <meta property="og:site_name" content="The Daily Californian"/>
        <meta property="article:publisher" content="https://www.facebook.com/dailycal"/>
        <meta property="fb:admins" content="877855486"/>
        {% block viewport %}<meta name="viewport" content="width=device-width, initial-scale=1.0">{% endblock %}
        {% block extra-meta %}{% endblock %}
    {% endblock %}

    {% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.6/dt-1.10.12/sc-1.4.2/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'browser/css/style.css' %}"/>
    {% endblock %}
    {% block js %}
    <script src="{% static 'browser/js/jquery.min.js' %}"></script>
    <script src="{% static 'browser/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'browser/js/fa.js' %}"></script>
    <script src="{% static 'browser/js/datatables.min.js' %}"></script>
    <script src="//www.dailycal.org/google-analytics-js/" type="text/javascript"></script>
    {% endblock %}
</head>
<body>
    {% include 'browser/navbar.html' %}
    {% block top %}{% endblock %}
    {% block container %}
    <div class="container">
        {% block breadcrumbs-container %}
        <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ol class="breadcrumb">
                {% block breadcrumbs %}{% endblock %}
            </ol>
        </div>
        </div>
        {% endblock %}
        {% block content %}{% endblock %}
    </div>
    {% endblock %}
    <footer class="footer">
      <div class="container">
        <p>Questions, comments or corrections? Email <a href="mailto:projects@dailycal.org">projects@dailycal.org</a>. Data and code is open-source on <a href="https://github.com/dailycal-projects">GitHub</a>. <br>
        Support innovative, independent student journalism. <a href="https://donate.dailycal.org/">Donate today.</a> <br>
        Copyright © 2016 The Daily Californian, The Independent Berkeley Student Publishing Co., Inc.</p>
      </div>
    </footer>
    {% block extra-js %}{% endblock %}
</body>
</html>

browser/templates/browser/context.html
{% extends 'browser/base.html' %}

{% block title %} Context | {{ block.super }} {% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}">Home</a></li>
<li class="active">Context</li>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-8">
	<h2>Departmental disparities</h2>

	<p>Last year, more than 15 members of the UC Berkeley <a href="{% url 'department_detail' 'economics' %}">economics department</a> faculty were paid more than $300,000. Not a single faculty member who teaches solely in the <a href="{% url 'department_detail' 'ethnic-studies' %}">ethnic studies department</a> made more than $200,000. The chair of the <a href="{% url 'department_detail' 'rhetoric' %}">rhetoric department</a> earned only $135,000.</p>

	<p>Disparities in faculty pay between UC Berkeley departments reflect a national trend. Universities across the country pay professors and lecturers of business, economics, law and engineering far more than faculty in the humanities and social sciences. Still, the differences at UC Berkeley are striking.</p>

	<p>Take, for example, <a href="{% url 'person_detail' 'sanjam-garg' %}">Sanjam Garg</a>, an assistant professor of computer science who was paid about $210,000 in 2015, his second year at UC Berkeley. Assistant professors are of lower rank than associate professors and full professors. But Garg made more last year than <a href="{% url 'person_detail' 'shari-huhndorf' %}">Shari Huhndorf</a>, the chair of the ethnic studies department, who was paid about $180,000.</p>

	<p>In the 1980s, the university established <a href="http://www.ucop.edu/academic-personnel-programs/compensation/2016-17-academic-salary-scales.html">salary scales</a> for business and engineering professors that were different from those for professors in other departments, according to a <a href="http://vpf.berkeley.edu/sites/default/files/Equity%20Study%20Report%20final%201-26-15%20--revised.pdf">campus report</a>. Today, a faculty member at the full professor rank can expect to be paid at least $86,800 — unless they teach business, economics or engineering, in which case the salary guideline is $106,700. A law professor can expect at least $146,200.</p>

	<p>In the early 2000s, the budget committee of the Academic Senate "accepted the reality of disciplinary market forces and described salary equity in terms relativized to discipline," according to the report.</p>

	<p>But faculty are often paid above the salary scales published by the university. <a href="{% url 'person_detail' 'shachar-kariv' %}">Shachar Kariv</a>, the chair of the economics department, was paid $508,000 last year, making him the highest-paid professor at UC Berkeley. More than 15 other faculty members were paid more than $400,000. All but two of them were in the economics, business or law departments.</p>

	<p>According to the campus report, current salary practices are necessary for recruiting and keeping faculty. Without them, UC Berkeley would be "unable to recruit as successfully as it has; the campus would lose many valued colleagues to other universities; and other universities would step up their efforts to recruit faculty away from Berkeley," the report said.</p>

	<p>Salaries at UC Berkeley lag behind those of private institutions, though the gap is larger for faculty at many other public schools. According to a <a href="https://www.aaup.org/reports-publications/2014-15salarysurvey">report</a> from the American Association of University Professors, the average salary of full professors at UC Berkeley for the 2014-15 academic year was about $173,000, while the average across private universities without religious affiliation was about $178,000. At Stanford University, the average salary was about $224,000, while the average for full professors at public universities was about $130,000.</p>

	<p>"The UC salary scales are not salary guidelines, rather they indicate the minimum salary that can be paid based on a professor’s rank and, loosely, amount of experience," said Benjamin Hermalin, the campus vice provost for the faculty, in an email. "It has been long recognized by the Office of the President and others that the salary scales are seriously below market."</p>
</div>
</div>
{% endblock %}

browser/templates/browser/department_detail.html
{% extends 'browser/base.html' %}
{% load humanize %}

{% block title %} {{ object.canonical|title }} | {{ block.super }}{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}#database">Database</a></li>
<li><a href="{% url 'department_list' %}">Departments</a></li>
<li class="active">{{ object.canonical }}</li>
{% endblock %}

{% block content %}
	<div class="row">
	<div class="col-md-12">
		<h1>{{ object.canonical|title }}</h1>

		<section>
		<h2>Average pay by title, 2015</h2>
			<table class="table table-striped">
			<thead>
			<tr>
				<th>Category</th>
				<th width="40%" class="right">Avg. salary in {{ object.canonical }}</th>
			</tr>
			</thead>
			<tbody>
			{% for category in by_title_category %}
			<tr>
				<td>{{ category.title_category|title }}</td>
				<td class="right">${{ category.gross__avg|floatformat:"2"|intcomma }}</td>
			</tr>
			{% endfor %}
			</tbody>
			</table>
		</section>

		<section>
			<h2>All {{ object.canonical|title }} faculty</h2>
			<br>
			<table id="person-list" class="table table-striped">
			<thead>
			<tr>
				<th>Name</th>
				<th>Rank</th>
				<th class="right">Salary (2015)</th>
			</tr>
			</thead>
			<tbody>
			{% for directoryrecord in object.directoryrecord_set.all %}
			{% with directoryrecord.person as person %}
			{% if person.latest_record.year == '2015' %}
			<tr>
				<td><a href="{% url 'person_detail' person.slug %}">{{ person.last|title }}, {{ person.first|title }}</a></td>
				<td>{{ person.latest_record.title_category|title }}</td>
				<td class="right">${{ person.latest_record.gross|intcomma }}</td>
			</tr>
			{% endif %}
			{% endwith %}
			{% endfor %}
			</tbody>
			</table>
		</section>

		<br> 
	</div>
	</div>
{% endblock %}

{% block extra-js %}
<script type="text/javascript">
$(document).ready(function() {
    $('#person-list').DataTable( {
    	scrollY: 400,
    	scroller: true,
    	info: false,
    	dom: "<'row'<'col-sm-6'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
    });
} );
</script>
{% endblock %}

browser/templates/browser/department_list.html
{% extends 'browser/base.html' %}
{% load humanize %}

{% block title %} Departments | {{ block.super }}{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'home' %}#database">Database</a></li>
<li class="active">Departments</li>
{% endblock %}

{% block content %}
	<div class="row">
	<div class="col-md-8">
		<section>
		<h2>Average salary by department, 2015</h2>
		<p><a href="{% url 'context' %}">Read about departmental disparities and the university's salary policy.</a></p>
		<p>Faculty members are compensated according to, among other factors, the length of their tenure at the university. Because departments are composed of faculty members with varying levels of experience, salary differences between departments — even within a particular title category — are not due exclusively to the academic discipline itself.</p>
		<p>These averages reflect only the faculty members we've chosen to analyze. That list is not exhaustive. <a href="{% url 'about' %}#caveats">Find out more about our methodology.</a></p>
		</section>
	</div>
	</div>

	<div class="row">
	<div class="col-md-12">
		<section>
		<table id="department-list" class="table table-striped">
		<thead>
		<tr>
			<th>Department</th>
			<th width=16% class="right">All</th>
			<th width=16% class="right">Professor</th>
			<th width=16% class="right">Associate professor</th>
			<th width=16% class="right">Assistant professor</th>
			<th width=16% class="right">Lecturer</th>
		</tr>
		</thead>
		<tbody>
		{% for d in object_list %}
		{% if d.canonical and d.avg_salary_2015 > 0 %}
		<tr>
			<td><a href="{% url 'department_detail' d.slug %}">{{ d.canonical }}</a></td>
			<td class="right">${{ d.avg_salary_2015|floatformat:"0"|intcomma }}</td>
			<td class="right">{% if d.avg_salary_professor %}${{ d.avg_salary_professor|floatformat:"0"|intcomma }}{% else %} - {% endif %}</td>
			<td class="right">{% if d.avg_salary_associate_professor %}${{ d.avg_salary_associate_professor|floatformat:"0"|intcomma }}{% else %} - {% endif %}</td>
			<td class="right">{% if d.avg_salary_assistant_professor %}${{ d.avg_salary_assistant_professor|floatformat:"0"|intcomma }}{% else %} - {% endif %}</td>
			<td class="right">{% if d.avg_salary_lecturer %}${{ d.avg_salary_lecturer|floatformat:"0"|intcomma }}{% else %} - {% endif %}</td>
		</tr>
		{% endif %}
		{% endfor %}
		</tbody>
		</table>
		</section>
	</div>
	</div>
{% endblock %}

{% block extra-js %}
<script type="text/javascript">
$(document).ready(function() {
    $('#department-list').DataTable( {
    	paging: false,
    	info: false,
    	order: [[1, 'desc']],
    	dom: "<'row'<'col-sm-12'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
    });
} );
</script>
{% endblock %}

browser/templates/browser/home.html
{% extends 'browser/base.html' %}
{% load humanize %}

{% block breadcrumbs-container %}{% endblock %}

{% block top %}
<div class="top">
	<div class="container">
	<section class="row">
		<div class="col-md-8 col-md-offset-2 text">
			<h1>Professor pay-checker</h1>
			<p class="byline">By <a href="http://www.dailycal.org/author/schinoy/">SAHIL CHINOY</a> &middot; September 20, 2016</p>
			<br>
			<p class="lead center">The Daily Californian processed the last decade of payroll information for UC Berkeley faculty, creating the most complete, searchable database of professor and lecturer pay by campus department.</p>
			<p class="lead center">We're also releasing the data as part of an <a href="{% url 'about' %}#project">open-source effort</a> to make faculty compensation information accessible to the public.</p>
			<p class="lead center"><a href="#database">Browse the database</a>, <a href="{% url 'context' %}">read context about departmental disparities</a> or <a href="{% url 'about' %}">find out more about the data</a>.</p>
		</div>
	</section>
	</div>
</div>
{% endblock %}

{% block content %}
	<section id="database" class="row">
		<div class="col-md-10 col-md-offset-1">
			<div style="text-align: center">
				<h2>Browse the database</h2>
				<p><a href="{% url 'department_list' %}">Compare department averages</a>.<br>
				Don't see a professor or lecturer? <a href="{% url 'about' %}#caveats">This might be why</a>.</p>
			</div>
			<br>
			<div id="loading-text" style="text-align: center;">
				<p class="lead">Loading...</p>
			</div>
			<div id="table-wrapper" class="hidden">
				<table id="person-list" class="table table-striped">
				<thead>
				<tr>
					<th>Name</th>
					<th>Rank</th>
					<th>Department</th>
					<th class="right">Salary (2015)</th>
				</tr>
				</thead>
				<tbody>
				{% for record in object_list %}
				<tr>
					<td><a href="{% url 'person_detail' record.person.slug %}">{{ record.person.last|title }}, {{ record.person.first|title }}</a></td>
					<td>{{ record.person.latest_record.title_category|title }}</td>
					<td>{% if record.person.directory_record.department_obj.canonical %}<a href="{% url 'department_detail' record.person.directory_record.department_obj.slug %}">{{ record.person.directory_record.department_obj.canonical }}</a>{% endif %}</td>
					<td class="right">${{ record.gross|intcomma }}</td>
				</tr>
				{% endfor %}
				</tbody>
				</table>
			</div>
		</div>
	</section>
{% endblock %}

{% block extra-js %}
<script type="text/javascript">
$(document).ready(function() {
    $('#person-list').DataTable( {
    	scrollY: 400,
    	scroller: true,
    	dom: "<'row'<'col-sm-12'f>>" +
		"<'row'<'col-sm-12'tr>>" +
		"<'row'<'col-sm-5'i><'col-sm-7'p>>",
    	initComplete: function(settings, json) {
    		$('#loading-text').addClass('hidden');
    		$('#table-wrapper').removeClass('hidden');
  		},
    });
} );
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
});
</script>
{% endblock %}

browser/templates/browser/navbar.html
<nav class="navbar navbar-dc navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a href="http://www.dailycal.org/" class="navbar-brand">the Daily Californian</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'context' %}">Context</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li class="nav-link"><a href="https://www.facebook.com/sharer/sharer.php?u=projects.dailycal.org/paychecker/"><i class="fa fa-lg fa-facebook"></i></a></li>
                <li class="nav-link"><a href="https://twitter.com/intent/tweet?url=projects.dailycal.org%2Fpaychecker&via=dailycal&text=Professor%20Pay-checker&"><i class="fa fa-lg fa-twitter"></i></a></li>
              </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>